export enum EventMenuChannels {
  WindowClose = 'window-close',
  WindowFixed = 'window-fixed',
  WindowMinimize = 'window-minimize',
  WindowMaximize = 'window-maximize',
  WindowToggleMaximize = 'window-toggle-maximize',
  WebUndo = 'web-undo',
  WebRedo = 'web-redo',
  WebCut = 'web-cut',
  WebCopy = 'web-copy',
  WebPaste = 'web-paste',
  WebDelete = 'web-delete',
  WebSelectAll = 'web-select-all',
  WebReload = 'web-reload',
  WebForceReload = 'web-force-reload',
  WebToggleDevtools = 'web-toggle-devtools',
  WebActualSize = 'web-actual-size',
  WebZoomIn = 'web-zoom-in',
  WebZoomOut = 'web-zoom-out',
  WebToggleFullscreen = 'web-toggle-fullscreen',
  UpdateTitle = 'update-title',
  OpenUrl = 'open-url',
}
